name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Update code on server
        run: |
          sshpass -p your_ssh_password ssh user@your-server-ip "docker exec cons-be bash -c 'git pull && exit' && docker restart cons-be"
        env:
          your_ssh_password: ${{ secrets.YOUR_SSH_PASSWORD }}
