name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Into Remote Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Chạy lệnh terminal trên máy chủ từ xa
            echo "Hello, World"
      
      - name: Run Terminal Command
        run: |
          # Đây là nơi để bạn đặt lệnh terminal bạn muốn chạy
          # Ví dụ: npm install && npm test
          echo "Hello, World"
