name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Sử dụng action để kiểm tra mã nguồn từ repository

      - name: Update code on server
        run: |
          sshpass -p your_ssh_password ssh root@206.189.84.20 "docker exec cons-be bash -c 'git pull && exit' && docker restart cons-be"
        env:
          your_ssh_password: ${{ secrets.YOUR_SSH_PASSWORD }}
